"""Pseudocode listings shown (and line-highlighted) next to each animation."""

PSEUDO_TREE = {
    "In-order": [
        "inorder(node):",
        "  if node is null: return",
        "  inorder(node.left)",
        "  visit(node)",
        "  inorder(node.right)",
    ],
    "Pre-order": [
        "preorder(node):",
        "  if node is null: return",
        "  visit(node)",
        "  preorder(node.left)",
        "  preorder(node.right)",
    ],
    "Post-order": [
        "postorder(node):",
        "  if node is null: return",
        "  postorder(node.left)",
        "  postorder(node.right)",
        "  visit(node)",
    ],
    "Level-order": [
        "queue = [root]",
        "while queue is not empty:",
        "  node = queue.pop_front()",
        "  visit(node)",
        "  push node.left and node.right (if any)",
    ],
    "Search (BST)": [
        "node = root",
        "while node is not null:",
        "  if target == node.key: return found",
        "  node = node.left if target < node.key else node.right",
        "return not found",
    ],
    "Height": [
        "height(node):",
        "  if node is null: return 0",
        "  L = height(node.left)",
        "  R = height(node.right)",
        "  return 1 + max(L, R)",
    ],
    "AVL insert": [
        "insert(key):        # standard BST insert, then repair",
        "  walk down: go left if key < node else right",
        "  attach key as a new leaf",
        "  for each ancestor, bottom to top:",
        "    update height; bf = h(left) - h(right)",
        "    if |bf| > 1: rebalance",
        "      Left-Left   : rotate_right(node)",
        "      Right-Right : rotate_left(node)",
        "      Left-Right  : rotate_left(left), rotate_right(node)",
        "      Right-Left  : rotate_right(right), rotate_left(node)",
    ],
    "Min-heap build": [
        "insert(x):",
        "  A.append(x)       # add at the end",
        "  i = last index",
        "  while i > 0 and A[i] < A[parent(i)]:",
        "    swap(A[i], A[parent(i)])",
        "    i = parent(i)",
    ],
    "Min-heap extract": [
        "extract_min():",
        "  min = A[0]        # smallest is the root",
        "  A[0] = A.pop()    # last element moves to the root",
        "  i = 0",
        "  while a child is smaller than A[i]:",
        "    swap A[i] with its smaller child; i = child",
        "  output min",
    ],
}


PSEUDO_GRAPH = {
    "BFS": [
        "queue = [start]; mark start discovered",
        "while queue is not empty:",
        "  u = queue.pop_front()",
        "  visit(u)",
        "  for each neighbour v of u:",
        "    if v is already discovered: continue",
        "    mark v discovered; parent[v] = u",
        "    queue.push(v)",
    ],
    "DFS": [
        "dfs(u):",
        "  mark u visited",
        "  for each neighbour v of u:",
        "    if v is not visited:",
        "      dfs(v)",
        "  return    # u fully explored",
    ],
    "Dijkstra": [
        "dist[*] = inf;  dist[start] = 0",
        "pq = min-heap {(0, start)}",
        "while pq is not empty:",
        "  d, u = pq.pop_min()",
        "  if u is already finalized: continue",
        "  finalize u          # dist[u] is exact now",
        "  for each edge (u, v, w):",
        "    if d + w < dist[v]:",
        "      dist[v] = d + w; parent[v] = u; pq.push(v)",
        "path = follow parent[] back from target",
    ],
    "A*": [
        "open = {start};  g[start] = 0",
        "while open is not empty:",
        "  u = vertex in open with smallest f = g + h",
        "  if u == goal: return path",
        "  move u to closed",
        "  for each edge (u, v, w):",
        "    tentative = g[u] + w",
        "    if tentative < g[v]:",
        "      g[v] = tentative; parent[v] = u; open.add(v)",
        "return no path",
    ],
    "Components": [
        "count = 0",
        "for each vertex s in the graph:",
        "  if s is not visited:",
        "    count += 1;  flood-fill (BFS) from s, colouring vertices",
        "return count",
    ],
}


PSEUDO_SORT = {
    "Bubble sort": [
        "for end = n-1 down to 1:",
        "  swapped = false",
        "  for i = 0 to end-1:",
        "    if a[i] > a[i+1]:",
        "      swap(a[i], a[i+1])",
        "      swapped = true",
        "  if not swapped: break    # already sorted",
    ],
    "Selection sort": [
        "for i = 0 to n-2:",
        "  min = i",
        "  for j = i+1 to n-1:",
        "    if a[j] < a[min]: min = j",
        "  swap(a[i], a[min])",
    ],
    "Insertion sort": [
        "for i = 1 to n-1:",
        "  key = a[i];  j = i",
        "  while j > 0 and a[j-1] > a[j]:",
        "    swap(a[j-1], a[j])",
        "    j = j - 1",
    ],
    "Merge sort": [
        "mergesort(lo, hi):",
        "  if lo >= hi: return",
        "  mid = (lo + hi) / 2",
        "  mergesort(lo, mid);  mergesort(mid+1, hi)",
        "  merge(lo, mid, hi):",
        "    while both halves non-empty: compare their fronts",
        "      write the smaller one back into a[k]",
        "    write whatever is left over",
    ],
    "Quick sort": [
        "quicksort(lo, hi):",
        "  if lo >= hi: return",
        "  pivot = a[hi];  i = lo",
        "  for j = lo to hi-1:",
        "    if a[j] < pivot:",
        "      swap(a[i], a[j]);  i = i + 1",
        "  swap(a[i], a[hi])    # pivot lands in its final spot",
        "  quicksort(lo, i-1);  quicksort(i+1, hi)",
    ],
    "Heap sort": [
        "build_max_heap(a)",
        "for end = n-1 down to 1:",
        "  swap(a[0], a[end])      # max goes to the end",
        "  sift_down(a, 0, end)",
        "sift_down(a, i, size):",
        "  largest = i;  l = 2i+1;  r = 2i+2",
        "  if l < size and a[l] > a[largest]: largest = l",
        "  if r < size and a[r] > a[largest]: largest = r",
        "  if largest != i: swap; sift_down(a, largest, size)",
    ],
}
